stockIdx = c(
'INDU	道瓊工業',
'OEX	S&P 100',
'SPX	S&P 500',
'CCMP	NASDAQ',
'NDX	NASDAQ 100',
'NYA	NYSE綜合',
'NYE	NYSE能源',
'NYK	NYSE金融',
'RIY	羅素1000',
'RTY	羅素2000',
'UTIL	道瓊公用事業',
'VIX	VIX波動率',
'VXD	VXD道瓊波動',
'VXN	VXN納指波動',
'SPTSX	加拿大',
'MERVAL	阿根廷',
'MEXBOL	墨西哥',
'IBOV	巴西股市',
'IGBVL	秘魯股市',
'IPSA	智利股市',
'IBVC	委內瑞拉',
'COLCAP	哥倫比亞',
'JMSMX	牙買加',
'SX5E	道瓊歐洲50',
'CAC	法國股市',
'DAX	德國股市',
'UKX	英國股市',
'AEX	荷蘭股市',
'ASE	希臘股市',
'HEX	芬蘭股市',
'ICEXI	冰島股市',
'KFX	丹麥股市',
'OBX	挪威股市',
'OMX	瑞典股市',
'PX	捷克股市',
'SMI	瑞士股市',
'WIG	波蘭股市',
'ATX	奧地利',
'BEL20	比利時',
'BET	羅馬尼亞',
'BUX	匈牙利',
'BVLX	葡萄牙',
'ISEQ	愛爾蘭',
'ITLMS	義大利',
'LUXXX	盧森堡',
'MADX	西班牙',
'RTSI	俄羅斯',
'SOFIX	保加利亞',
'EGX30	埃及股市',
'TOP40	南非股市',
'DFMGI	杜拜股市',
'TA35	以色列',
'XU100	土耳其',
'HSI	香港恆生',
'HSP	恆生地產',
'HSTECH	恆生科技',
'CHINEXT	創業板指',
'HKSPGEM	香港創業板',
'HSCCI	香港紅籌',
'HSCEI	香港國企',
'SHASHR	上海A股',
'SHBSHR	上海B股',
'SHCOMP	上海綜合',
'SHSZ300	滬深300',
'SZASHR	深圳A股',
'SZBSHR	深圳B股',
'SZSME	中小板指',
'SICOM	深證成指',
'SIN	邪惡指數',
'NKY	日經225',
'TSEREIT	東證REIT',
'TWOTCI	台灣店頭',
'TWSE	台灣加權',
'KOSPI	韓國股市',
'JCI	印尼股市',
'VNINDEX	越南股市',
'SET	泰國股市',
'SENSEX	印度股市',
'FSSTI	新加坡',
'KLCI	馬來西亞',
'KSE	巴基斯坦',
'AS30	澳洲股市',
'NZSE50FG	紐西蘭'
)

commodityIdx = c(
'COMMALUM	鋁',
'COMMCOPP	銅',
'COMMGOLD	黃金',
'COMMLEAD	鉛',
'COMMNIKL	鎳',
'COMMPALL	鈀',
'COMMPLAT	白金',
'COMMRHDM	銠',
'COMMSILV	銀',
'COMMZINC	鋅',
'FUTRBEAN	黃豆期貨',
'FUTRBNOL	黃豆油期貨',
'FUTRBOIL	布蘭特油期',
'FUTRCATT	活牛期貨',
'FUTRCOCO	可可豆期',
'FUTRCOFF	咖啡C期',
'FUTRCOPP	銅期貨',
'FUTRCORN	玉米期貨',
'FUTRCTTN	二號棉期',
'FUTRGOLD	黃金期貨',
'FUTRHOGS	瘦豬期貨',
'FUTRHOIL	燃油期貨',
'FUTRNGAS	天然氣期',
'FUTRRBOB	無鉛汽油',
'FUTRSILV	銀期貨',
'FUTRSUGR	十一號糖',
'FUTRWHEA	小麥期貨',
'FUTRWOIL	紐約輕原油'
)

forexIdx = c(
'AUDUSD	澳幣/美元',
'EURUSD	歐元/美元',
'GBPUSD	英鎊/美元',
'NZDUSD	紐幣/美元',
'USDARS	美元/阿根廷',
'USDBRL	美元/巴西幣',
'USDCAD	美元/加幣',
'USDCHF	美元/瑞士法郎',
'USDCLP	美元/智利',
'USDCNY	美元/人民幣',
'USDHKD	美元/港幣',
'USDHUF	美元/匈牙利幣',
'USDIDR	美元/印尼盾',
'USDILS	美元/以色列幣',
'USDINR	美元/印度盧比',
'USDJPY	美元/日圓',
'USDKRW	美元/韓圜',
'USDMAD	美元/摩洛哥',
'USDMXN	美元/墨披索',
'USDMYR	美元/馬來幣',
'USDPHP	美元/菲披索',
'USDRUB	美元/俄盧布',
'USDSEK	美元/瑞典克朗',
'USDSGD	美元/新元',
'USDTHB	美元/泰銖',
'USDTRY	美元/土耳其幣',
'USDTWD	美元/台幣',
'USDZAR	美元/南非幣'
)

otherIdx = c(
'BCI	波羅的海海岬型',
'BCTI	波羅的海成品油',
'BDI	波羅的海乾散貨',
'BDTI	波羅的海原油',
'BHI	波羅的海輕便型',
'BPI	波羅的海巴拿馬',
'BSI	波羅的海極限型',
'BIBCBA	BC綜合公債',
'BIBCMGBK	BC美國房貸債',
'BIBCUSAI	BC美國機構債',
'BIBCUSGC	美國政府&公司債',
'BIJPGDE	JP德國政府債',
'BIJPGEM	JP新興政府債',
'BIJPGEU	JP歐盟政府債',
'BIJPGFR	JP法國政府債',
'BIJPGG	JP全球政府債',
'BIJPGUK	JP英國政府債',
'BIMLCO	ICE美國公司債',
'JGENVUUG	JP新興當地債',
'BIMLCCC	ICE CCC債券',
'BIMLFHLMC	ICE美國房地美',
'BIMLCOHY	ICE美國高收益',
'BIMLFNMA	ICE美國房利美',
'BIMLGNMA	ICE美國吉利美',
'BIMLHY100	ICE高收益100',
'BIMLHYEU	ICE歐洲高收益',
'BIMLHYG	ICE全球高收益',
'ELAU	澳洲不動產',
'ELJP	日本不動產',
'ELUK	英國不動產',
'EXUK	歐陸不動產',
'UPRA	歐洲不動產',
'ADSMI	阿布達比',
'USD	美元指數',
'XAD	澳幣指數',
'XBP	英鎊指數',
'XEU	歐元指數',
'XJY	日圓指數',
'XSF	瑞郎指數',
'MS101	中華指數',
'MS103	遠東指數',
'MS110	澳洲指數',
'MS118	菲律賓指數',
'MS304	美國指數',
'MS001	世界指數',
'MS114	中國',
'MS201	歐洲',
'MS212	俄羅斯',
'MS305	巴西',
'MS113	韓國',
'MS115	台灣',
'MS119	泰國',
'MS120	馬來西亞',
'MS121	印尼',
'MS122	印度',
'MS207	新興東歐',
'MS214	土耳其',
'MS302	新興拉美',
'MS402	歐非中東',
'MS414	南非',
'MS007	金磚四國',
'MS008	新興市場',
'MS009	邊境市場',
'MS105	太平洋',
'MS108	AC亞太',
'MS109	新興亞洲',
'BKX	NASDAQ銀行',
'BPGDM	金礦商看漲',
'BTK	AMEX生技',
'CRBAX	CRB農業',
'CRBIX	CRB工業金屬',
'DDX	電腦碟片',
'DJCISIP	S&P道瓊白銀',
'DJGSP	道瓊貴金屬',
'DJR	道瓊REITs',
'DJUSCA	道瓊美國博奕',
'DJUSMG	道瓊美國礦產',
'ET50	ET50環境科技',
'BIMLHY	ICE高收益指數',
'CRB	CRB指數',
'DJUSWU	水指數',
'MS102	金龍指數',
'FTMIGMI	FTSE金礦',
'FVX	5年期票利率',
'HWI	電腦硬體',
'INSR	NASDAQ保險',
'IRX	3月期票利率',
'JSDA	JASDAQ',
'NBI	NBI生技',
'PCOMP	菲律賓',
'RAG	羅素3000成長',
'RAV	羅素3000價值',
'RAY	羅素3000',
'SOX	費城半導體',
'W1BSC	世界原料',
'RICI	Roger商品',
'SPGSCIP	高盛商品',
'SPGSREP	綜合商品',
'RICIA	Rogers農產',
'RICIM	Rogers金屬',
'SPGSAGP	高盛農產品',
'SPGSINP	基本金屬',
'SPGSLVP	高盛牲畜',
'SPGSPMP	高盛貴金屬',
'GDM	黃金礦業',
'SPGSGC	高盛黃金',
'SPGSGCP	高盛黃金',
'HUI	AMEX金蟲',
'TNX	10年利率',
'TPX	東證一部',
'TRAN	道瓊交通',
'TSE2	東證二部',
'TYX	30年債殖利率',
'WAGR	全球博奕',
'XAL	AMEX航空',
'XAU	費城金銀',
'XBD	NYSE券商',
'XCI	電腦科技',
'XNG	天然氣',
'XOI	AMEX石油',
'AGIGL	替代能源',
'ECO	WH乾淨能源',
'IXE	AMEX能源',
'RICIE	Rogers能源',
'SPGSENP	高盛能源',
'WCATI	CRB能源開採',
'OSX	費城油業'
)

batchList = c(
'INDU', '道瓊工業', '1',
'VXD', 'VXD道瓊波動', '1',
'SX5E', '道瓊歐洲50', '1',
'DAX', '德國股市', '1',
'UKX', '英國股市', '1',
'HSP', '恆生地產', '1',
'HSTECH', '恆生科技', '1',
'CHINEXT', '創業板指', '1',
'SHASHR', '上海A股', '1',
'SZASHR', '深圳A股', '1',
'SZSME', '中小板指', '1',
'NKY', '日經225', '1',
'TWSE', '台灣加權', '1',
'KOSPI', '韓國股市', '1',
'FSSTI', '新加坡', '1',
'AS30', '澳洲股市', '1',
'COMMALUM', '鋁', '2',
'COMMCOPP', '銅', '2',
'COMMNIKL', '鎳', '2',
'FUTRBEAN', '黃豆期貨', '2',
'FUTRHOIL', '燃油期貨', '2',
'FUTRNGAS', '天然氣期', '2',
'EURUSD', '歐元/美元', '3',
'GBPUSD', '英鎊/美元', '3',
'USDCNY', '美元/人民幣', '3',
'USDRUB', '美元/俄盧布', '3',
'BDI', '波羅的海乾散貨', '4',
'USD', '美元指數', '4'
)
batchIdx <- matrix(batchList, ncol=3, byrow = TRUE)

stockIdxMenu <- matrix(unlist(strsplit(stockIdx, split = "\\t")), ncol=2, byrow=TRUE)
commodityIdxMenu <- matrix(unlist(strsplit(commodityIdx, split = "\\t")), ncol=2, byrow=TRUE)
forexIdxMenu <- matrix(unlist(strsplit(forexIdx, split = "\\t")), ncol=2, byrow=TRUE)
otherIdxMenu <- matrix(unlist(strsplit(otherIdx, split = "\\t")), ncol=2, byrow=TRUE)
